---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9617'
    spec:
      containers:
      - name: exporter
        image: ekofr/pihole-exporter:0.0.9
        imagePullPolicy: IfNotPresent
        env:
        - name: PIHOLE_HOSTNAME
          value: localhost
        
        - name: PIHOLE_PASSWORD
          value: VMware1!
        
        - name: INTERVAL
          value: 30s
        
        - name: PORT
          value: '9617'
        
        ports:
        - containerPort: 9617
          name: exporterport
          protocol: TCP
        
        livenessProbe:
          httpGet:
            path: /liveness
            port: 9617
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9617

      - name: pihole
        image: pihole/pihole:v5.1.2
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Manila

        - name: WEBPASSWORD
          value: VMware1!

        - name: VIRTUAL_HOST
          value: pihole.dr.ldc.int
        
        - name: DNS1
          value: 1.1.1.1

        - name: DNS2
          value: 8.8.8.8
        
        - name: CONDITIONAL_FORWARDING
          value: 'true'
        
        - name: CONDITIONAL_FORWARDING_DOMAIN
          value: ldc.int

        - name: CONDITIONAL_FORWARDING_IP
          value: 172.16.0.100
        
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole

        livenessProbe:
          tcpSocket:
            port: 53
          initialDelaySeconds: 15
          periodSeconds: 30
        
        readinessProbe:
          tcpSocket:
            port: 53
          # exec:
          #   command: ['dig', '@127.0.0.1', 'cnn.com']
          timeoutSeconds: 20
          initialDelaySeconds: 5
          periodSeconds: 60
      
      volumes:
      - name: etc-pihole
        emptyDir:
          medium: Memory