apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: pihole
  annotations:
        metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  ports:

    - protocol: UDP
      name: dns-udp
      port: 53
      targetPort: 53
    
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 172.16.10.210
  selector:
    app: pihole