apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

bases:
- ../_base

patchesStrategicMerge:
- deployment-patch.yaml
- deployment-replica.yaml
- deployment-pod-name.yaml
- service-dns-tcp-ip.yaml
- service-dns-udp-ip.yaml